apiVersion: v1
kind: Secret
metadata:
  name: fastood-db-secret
type: Opaque
stringData:
  DB_HOST: jdbc:mariadb://fastood-db:3306/fiap-fastfood
  DB_USER: fiap_postech
  DB_PASS: fiap
  MARIADB_DATABASE: fiap-fastfood
  MARIADB_ROOT_PASSWORD: rootfiap
  MARIADB_USER: fiap_postech
  MARIADB_PASSWORD: fiap